### ISSUE TITLE
使用data_gen_loc生成fvb中的data，并将data.py中的num_dataset改为8之后使用train.py进行训练，但是会报错

### ISSUE THREAD

**Issue by FelixFinnDu** [lu-group/fourier-deeponet-fwi#1]
代码按照上面修改过，使用的Windows环境下torch 2.0.0+cu118；numpy 1.26.4；DeepXDE 1.12.2；
我把生成的data1和openfwi上下载对应的data1发现是一致的，便使用data_gen_loc生成的数据；
其中还将路径修改为windows环境读取的路径
报错信息如下：
Using backend: pytorch
Other supported backends: tensorflow.compat.v1, tensorflow, jax, paddle.
paddle supports more examples now and is recommended.
X_train_branch shape: (4000, 5, 1000, 70), X_train_trunk shape: (4000, 5)

X_test_branch shape: (50, 5, 1000, 70), X_test_trunk shape: (50, 5)

y_train shape: (4000, 1, 70, 70), y_test shape: (50, 1, 70, 70)
Compiling model...
'compile' took 0.000319 s

Training model...

Step      Train loss    Test loss     Test metric
0         [5.16e-01]    [4.72e-01]    [4.72e-01, 5.62e-01]    
Traceback (most recent call last):
  File "i:\ai4Science\models\fourier-deeponet-fwi-main\src\train.py", line 72, in <module>
    main(dataset='fvb', task='loc')
  File "i:\ai4Science\models\fourier-deeponet-fwi-main\src\train.py", line 65, in main
    losshistory, train_state = model.train(iterations=100000, batch_size=32, display_every=100, callbacks=[checker])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\deepxde\utils\internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\deepxde\model.py", line 657, in train
    self._train_sgd(iterations, display_every)
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\deepxde\model.py", line 675, in _train_sgd
    self._train_step(
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\deepxde\model.py", line 567, in _train_step
    self.train_step(inputs, targets, auxiliary_vars)
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\deepxde\model.py", line 364, in train_step
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\deepxde\model.py", line 364, in train_step
    self.opt.step(closure)
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\torch\optim\lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\torch\optim\optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\torch\optim\optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\torch\optim\adam.py", line 141, in step
    adam(
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\torch\optim\adam.py", line 281, in adam
    func(params,
  File "D:\Users\23905\anaconda3\envs\pytorch\Lib\site-packages\torch\optim\adam.py", line 442, in _multi_tensor_adam
    device_grads = torch._foreach_add(device_grads, device_params, alpha=weight_decay)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (2) must match the size of tensor b (20) at non-singleton dimension 4
由于在train之后便报了库中的问题，所以想请教一下解决办法，万分感激

**Comment by FelixFinnDu** [comment]
将num_dataset更改为48后训练仍然报了相同的错误，不知是否与库的版本有关

**Comment by FelixFinnDu** [comment]
与安装的库版本有关，暂不清楚与具体哪一个有关
一下版本可以运行
Package            Version
------------------ -----------
Brotli             1.0.9
certifi            2024.8.30
charset-normalizer 3.3.2
contourpy          1.3.1
cycler             0.12.1
DeepXDE            1.12.2
filelock           3.13.1
fonttools          4.54.1
gmpy2              2.1.2
idna               3.7
Jinja2             3.1.4
joblib             1.4.2
kiwisolver         1.4.7
MarkupSafe         2.1.3
matplotlib         3.9.2
mkl_fft            1.3.11
mkl_random         1.2.8
mkl-service        2.4.0
mpmath             1.3.0
networkx           3.2.1
numpy              2.0.1
packaging          24.2
pandas             2.2.3
pillow             10.4.0
pip                24.2
pyaml              24.9.0
pyparsing          3.2.0
PySocks            1.7.1
python-dateutil    2.9.0.post0
pytz               2024.2
PyYAML             6.0.2
requests           2.32.3
scikit-learn       1.5.2
scikit-optimize    0.10.2
scipy              1.14.1
setuptools         75.1.0
six                1.16.0
sympy              1.13.2
threadpoolctl      3.5.0
torch              2.5.1
torchaudio         2.5.1
torchvision        0.20.1
triton             3.1.0
typing_extensions  4.11.0
tzdata             2024.2
urllib3            2.2.3
wheel              0.44.0

**Comment by FelixFinnDu** [comment]
python=3.10.15
